---
# aireos_command does not support network_cli
ansible_network_os: "aireos"
ansible_connection: "local"
provider:
  host: "{{ inventory_hostname }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_password }}"

command_list:
  - "show wlan summary"
  - "show inventory"
  - "show license all"
  - "show boot"
...
