---
# As of v2.6.2, aireos_command does not support network_cli
ansible_connection: "local"
ansible_network_os: "aireos"
command_list:
  - "show wlan summary"
  - "show inventory"
  - "show license all"
  - "show boot"
...
