---
all:
  children:
    cisco_ios:
      hosts:
        csr1:
        csr2:
    cisco_asa:
      hosts:
        asav1:
    cisco_nxos:
      hosts:
        n9kv1:
    cisco_iosxr:
      hosts:
        xrv1:
    juniper_junos:
      hosts:
        vmx1:
    arista_eos:
      hosts:
        veos1:
    mikrotik_routeros:
      hosts:
        chr1:
    nokia_sros:
      hosts:
        sr1:
          ansible_host: "broken-dawn-7748.edge.mysocket.io"
          ansible_port: 58390
...
