---
collections:
  - "cisco.ios"
  - "cisco.iosxr"
  - "cisco.asa"
  - "cisco.nxos"
  - "arista.eos"
  - "junipernetworks.junos"
  - "community.routeros"  # Mikrotik RouterOS
  - "community.network"  # Cisco AireOS and Nokia SR-OS
  - "community.general"  # archive module
...
