---
# Log in and run the commands specified in the group_vars/ files.
- name: "EOS >> Gather Arista EOS information"
  arista.eos.eos_command:
    commands: "{{ command_list }}"
  register: "CLI_OUTPUT"
...
